name: carting
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^11.2.2
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  go_router: ^14.7.2
  flutter_spinkit: ^5.2.1
  dotted_border: ^2.1.0
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.1
  intl: ^0.19.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  logger: ^2.5.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.1
  formz: ^0.8.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.2
  internet_connection_checker: ^3.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image: ^4.5.2
  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  table_calendar: ^3.1.3
  http: ^1.2.2
  flex_dropdown: ^0.2.0
  animated_rating_bar: ^0.0.8
  path_provider: ^2.1.5
  open_filex: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.9.2
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/documents/
    - assets/fonts/Lufga-Medium.ttf
    - assets/fonts/Lufga-Regular.ttf

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/Lufga-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lufga-Medium.ttf
          weight: 500
